-- DEPRECATED: Duplicate of 009_atomic_counters_sync_state.sql
-- This file was erroneously numbered as 008. The real 008 migration is 008_system_health.sql.
-- Kept empty to avoid renumbering issues. See 009_atomic_counters_sync_state.sql for the actual migration.
